apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: scheduled-spark-job
  namespace: default
spec:
  schedule: "@every 2m"
  concurrencyPolicy: Forbid
  successfulRunHistoryLimit: 1
  failedRunHistoryLimit: 3
  suspend: false
  template:
    type: Python
    pythonVersion: "3"
    mode: cluster
    image: "sgrzegorz/sparkjob:latest"
    imagePullPolicy: IfNotPresent
    mainApplicationFile: local:///app/main.py
    sparkVersion: "3.2.0"
    restartPolicy:
      type: OnFailure
      onFailureRetries: 3
      onFailureRetryInterval: 10
      onSubmissionFailureRetries: 5
      onSubmissionFailureRetryInterval: 20
    driver:
      cores: 1
      coreLimit: "1000m"
      memory: "512m"
      labels:
        version: 3.2.0
      serviceAccount: sparkoperator-spark
    executor:
      cores: 1
      instances: 1
      memory: "512m"
      labels:
        version: 3.2.0
    deps:
      jars:
        - https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar
        - https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar
